defmodule HexaCore.Transpiler.RustGenerator do
  @moduledoc "Translates DSL Rule ASTs into pure Rust code."
  alias HexaCore.DSL.Rule

  @spec generate(list(Rule.t())) :: String.t()
  def generate(rules) do
    loops = Enum.map_join(rules, "\n", &generate_rule/1)

    """
    // AUTO-GENERATED BY HEXAPLANNER TRANSPILER
    // DO NOT EDIT MANUALLY

    use crate::domain::Problem;

    #[must_use]
    pub fn calculate_generated_score(problem: &Problem) -> i64 {
        let mut score = 0;

        #{loops}

        score
    }
    """
  end

  defp generate_rule(%Rule{
         entity: :job,
         field: :start_time,
         condition: :is_nil,
         penalty_score: score
       }) do
    """
        for job in &problem.jobs {
            if job.start_time.is_none() {
                score -= #{score};
            }
        }
    """
  end

  # Fallback for unsupported rules in MVP
  defp generate_rule(_), do: ""
end
